name: CI

on:
  push:
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev xvfb x11-xserver-utils

      - name: Build
        run: |
          make

      - name: (Optional) Test Run
        run: |
          # We run test.sh under Xvfb (a headless X server) to allow xmodmap.
          # The --auto-servernum ensures each job uses a unique server number,
          # and --server-args sets up a basic screen for Xvfb.
          xvfb-run --auto-servernum --server-args='-screen 0 1280x1024x24' bash ./test.sh

      - name: Test Flip Script
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1280x1024x24' bash ./test_flip_mouse.sh
